### PR TITLE
Multiple ircddb networks capability

### PR DESCRIPTION
**Pull request by F4FXL**
Hi,

This adds the ability to connect to multiple ircddb networks. What drove me to do this is that I migrated STN208 from the legacy software to Smart Group Server and it was no longer available on non Quadnet connected gateways.
This is largely based on the code I once wrote for the ircddbgateway and legacy starnet software. Non quadnet specific messages are not sent to non quadnet networks. It is running for 10 days now, haven't had any issue so far.
The config file requires a small change if it is already there.
While I value Quadnets approach I truly believe that balkanization of networks is not a good thing and there is nothing more frustrating than traveling and not being able to access your favorite group.

73
Geoffrey F4FXL / KC3FRA

### CODE REVIEW

**Comment by n7tae** [comment]
I would be delighted to accept this. However I feel very strongly that if you haven't set up an sgs.cfg file "make install" should fail! We have enough trouble with hotspot image producers (who shall go unnamed) who put their callsigns into a gateway config of their images. Then QuadNet has a name collision problem when users don't pay attention to what they are doing. Please fix that. You can move the sgs.cfg copy to the first command so it will fail right away.

**Comment by F4FXL** [comment]
Hi,

I am confused...
This is smart-group-server how is this supposed to land in a hotspot image?
The Makefile is not modified and install will fail if sgs.cfg is not present https://github.com/F4FXL/smart-group-server/blob/master/Makefile#L35 I had some merge conflicts maybe your commit got lost while resolving it. However as you can tell from the diff the file is identical.

**Comment by n7tae** [comment]
I think I probably got confused. Sorry! It's merged. Thanks for making the Smart Group Server smarter!

**Comment by n7tae** [comment]
BTW thanks for using stringstreams. I'm a very old school C programmer and still slow to adopt C++ stuff. These are much nicer than char arrays!

**Comment by F4FXL** [comment]
No issue ;) Maybe you are too deep into QnetGateway ;)  
Will you update the DStar1 group ?

**Comment by n7tae** [comment]
It's up to Jeff. Does group2 require registration?

**Comment by F4FXL** [comment]
I am programming c# for a living. Learned C++ 17 years ago, it has changed a lot since then. stringstream are just so easy to use, I actually learned about them while making this.

**Comment by F4FXL** [comment]
yes all of the ircddb.net servers require registration.  
For STN208 I requested an official repeater callsign (F1ZNZ) that i am using for this sole purpose.  
  
  
- - - - - -

  


Geoffrey Merck  
F4FXL / KC3FRA  
[http://www.f4fxl.org](http://www.f4fxl.org "Geoffrey Merck Website")

**Comment by n7tae** [comment]
Geoffrey, we're having some problems with multiclient so i moved your PR commits to a branch call "multiclient". master is back where it was.
Here's the problems: 1) we tried it on K7DIG and Jeff wasn't able to log into DSTAR3 from group2. 2) It's sending the SGS messages to openquad twice.

**Comment by F4FXL** [comment]
Hi Tom,  
  
Can you send me an excerpt of your config file? And also the output of the program when not started as a service.  
Which repeater did Jeff Try?  
I tried this weekend and had no issues logging in from a repeater (DB0DB) which is only on group1.  
  
Did you check on the server quadnet server side if the messages are sent twice? If the latter is the case you should also see them doubled on my STN208 groups.  
Jeff might have been confused by the output which is outputing the SGS messages as many times as you have network configured but actually only send it to the quadnet network. See here [https://github.com/n7tae/smart-group-server/blob/multiclient/IRCDDBClient.cpp#L124](https://github.com/n7tae/smart-group-server/blob/multiclient/IRCDDBClient.cpp#L124)  
Maybe i should check how the m_isQuadNet variable is initialised.

**Pull request merged**
