### PR TITLE
Changes to not run as root

### PR DESCRIPTION
**Pull request by K2IE**
These are the tested changes to run as user "sgs" rather than "root".  It addresses the concern that I raised in issue #6.

### CODE REVIEW

**Comment by n7tae** [comment]
Your paths to useradd, userdel and nologin don't work on Debian-based systems, they're in /usr/sbin/. Also, not sure why you broke the symbolic link to sgs.cfg.

**Comment by K2IE** [comment]
OK, I'll fix the paths.  They are actually in both places on Fedora, I
was thinking that they were in /sbin on Debian/Raspbian.
The reason that the symlink had to be broken has to do with
permissions.  When I first ran as sgs, it syslinked into my user home
dir and was denied.  It works for root, of course, because root...
The test with my callsign was just that, a test run after the
compile.  My actual server is running as WA2NYC, which is a club
callsign.
Will follow up in a bit...

**Comment by n7tae** [comment]
I need the symbolic link to sgs.cfg. It gets confusing if multiple people are administering the sgs and there are two copies of the configuration file.

**Comment by K2IE** [comment]
I don't recommend this from a security perspective.  Here's why:
User tom grabs the source and builds the software.  It ends up under
/home/tom.  Then he runs a sudo make install.  The symlink is created
as root has the ability to read anything.
However, no users other than root and tom have access to /home/tom by
default.  So user sgs cannot follow the symlink.
Could you make Tom's home directory world readable?  Well you could but
that would be less secure rather than more secure.  I'm thinking about
a shared environment at a cloud host rather than a Raspberry Pi in
someone's home.
If this is a preference that you can't get past you could reject the
pull request and I'll maintain my fork and I'll backport any changes
that arise in the future.  It ought to be clear to anyone administering
the server that the definitive copy is in /usr/local/etc, but no doubt
your desire is based upon real world issues.

**Pull request merged**
